### ISSUE TITLE
Admin cannot remove a texter from Spoke campaign using "dynamically assign contacts" feature

### ISSUE THREAD

**Issue by ErikKirkstein** [ProgressiveCoders/Spoke#629] opened 2018-06-11 15:51 UTC
When a texter is added to a Spoke campaign with "dynamically assign contacts" enabled, and Admin cannot remove them from the campaign.

Normally, a Spoke admin can either set a texter's assignment at "0" OR delete the texter by selecting the trash can icon and click "SAVE" to remove a texter from a Spoke campaign

This process should be enable for Spoke campaigns set to "dynamically assign contacts"

**Comment by schuyler1d** [comment] 2018-08-27 18:54
Some notes/codepoints

Code points for the user getting more dynamic assignments:
* On the client-side dynamic assignments are pulled/received here: https://github.com/MoveOnOrg/Spoke/blob/main/src/containers/TexterTodo.jsx#L135-L149
* The server side is here: https://github.com/MoveOnOrg/Spoke/blob/main/src/server/api/schema.js#L704-L760

Code points for assignment:
* server side: https://github.com/MoveOnOrg/Spoke/blob/main/src/server/api/schema.js#L176-L187
but note that a lot of our code might do 'something different' assumption-wise inside: https://github.com/MoveOnOrg/Spoke/blob/main/src/server/api/schema.js#L155-L166 and the [following job](https://github.com/MoveOnOrg/Spoke/blob/main/src/workers/jobs.js#L364)
* client-side is here: https://github.com/MoveOnOrg/Spoke/blob/main/src/components/CampaignTextersForm.jsx#L122 (note that onChange method is a beast! -- and has been a source of bugs/subtle-edge-cases in the past)

* This code is very relevant to the scaling work so worth going deeper with familiarity-- and it's also worth noting that the API might need to change slightly because [we want to get assignments/contacts in batches](https://github.com/MoveOnOrg/Spoke/issues/813)

Besides the [max contacts logic](https://github.com/MoveOnOrg/Spoke/blob/main/src/server/api/schema.js#L723-L736) there there are no real restrictions on the user.
Perhaps setting the max_contacts on the assignment in dynamic mode is buggy (and/or the interface isn't clear) -- maybe it doesn't accept a value of `0`, for example.

If that isn't acceptable or working at all anymore, then maybe some other condition could exist related to the user record that's tested -- e.g. a user blocklist status, etc.

**Comment by shakalee14** [comment] 2018-08-27 20:49
@sandramchung

The dynamic assignment feature allows you to assign texter(s) to a campaign without giving them a set contact list/count to work with.

Steps to get it working:

1. Create a campaign, when you get to the texter panel, turn `Dynamically assign contacts` toggle on.
2. A link should appear - this link allows you to share it with a texter - once the texter has accepted that link, they can be assigned to the campaign. The texter can also be assigned if they are already apart of this organization. 
3. You can either search for a texter and select them or click `add all` (clicking add all will add all texters in your organization to this campaign).
4. Once you have people selected, you technically are done (you do not have to fill in available to assign or max columns). 

<img width="1086" alt="screen shot 2018-08-27 at 4 42 33 pm" src="https://user-images.githubusercontent.com/16676323/44685090-9923d700-aa18-11e8-99da-b02a3a23abc5.png">

NOTE: If you fill in a value for 'Max', that will set the max amount of contacts that texter can do initial sends to.

5. Note - you may have to save and refresh (or do it 2x if it doesnt initially save)
6. Finish creating campaign.
7. As a texter that has been assigned to the campaign, you should be able to visit your texter home screen and see a panel for the campaign that looks similar to this:

<img width="1388" alt="screen shot 2018-08-27 at 4 38 59 pm" src="https://user-images.githubusercontent.com/16676323/44685064-8b6e5180-aa18-11e8-9e5f-c7d4ad260efe.png">

8. When there are no more texts to send, that button on the texter panel should grey out.

I tried to write down the steps after doing it a few times - let me know if this works for you and if you have any more questions. It would probably good to have this as documentation somewhere apart of an Admin FAQ (in the future/separate from this issue).

**Comment by sandramchung** [comment] 2018-08-27 21:19
Clarification needed: 

What do I do in the case where the texter to be deleted has already sent texts? Do we want to allow texter deletion from the assignment screen at all if they have sent texts already? Do we disable further dynamic assignment?

Here are my assumptions about the other cases:

- In the case that they don't have any assigned contacts, I simply delete them from the assignments table. 
- In the case where they have been assigned a single contact but haven't texted that contact yet, I delete the assignment and then return the assigned contact to the available contacts pool.

**Comment by sandramchung** [comment] 2018-08-27 21:31
Notes for myself on steps to reproduce:

- Create a campaign
- Turn on dynamic assignment
- Grab the join link (from clicking + at the People menu, not the one that pops up in the texter assignment screen when you enable dynamic assignment - the latter doesn't work in any browser and neither works in Firefox) and open it in a new browser/incognito window to join the org with a different user. May have to manually delete cached user to login.
- Add this texter to the campaign on the assignments screen in campaign edit
- Try deleting the texter from the campaign and saving.

**Comment by sandramchung** [comment] 2018-08-28 17:10
@ErikKirkstein Here's my read of the needs and a proposal based on it:

 1) It sounds like we need to stop people from being able to text through Spoke. I suspect it should be organization- or instance-wide, so they will be prevented from texting for any other campaigns in this Spoke org or Spoke instance (Is there any reason why someone should be blocked from one campaign but not another?). In that case I think we should handle it at the People admin level rather than in a particular campaign by assigning a "blocked" role that cuts off their access, per Sky's suggestion. Please correct/elaborate if I'm missing something here.

 2) When we block a texter, we need to handle the cascading implications. If they have already been assigned to a campaign and/or have sent texts, we:
 a) remove them from the available texters list
 b) show them in the assignment list as some sort of 'disabled' - type status
 c) set their max contacts to 0 on any existing assignments (this step doubles as a manual fix for now; though we should check if that does totally cut off their ability to text people they've already texted)
 d) return to the assignable pool any untexted contacts that were assigned to them
 e) block them from logging in (open to other ideas here)

 @shakalee14 and @rohangrover  - scope check?

**Comment by sandramchung** [comment] 2018-08-28 17:15
A quick and dirty solution could be to manually set max contacts to 0 and then add BLOCKED to their display name so that if you try to assign them in the future you'll get a visual warning not to do so.

**Comment by sandramchung** [comment] 2018-08-29 16:46
Implementing the manual (second) solution. Now to make sure setting max contacts to 0 actually prevents someone from texting ...

**Comment by shakalee14** [comment] 2018-08-30 17:26
We will need to handle #828 before fixing this - so @sandramchung will focus on that instead.

**Comment by shakalee14** [comment] 2018-09-03 19:05
@sandramchung after talking to Mark - we don't want to block texters from all texting - so adding a 'blocked' tag may not make sense currently. They are fine with us just fixing max_contacts.

**Comment by ibrand** [comment] 2019-09-02 22:55
Hey @ErikKirkstein and @sandramchung I'm cleaning up our `good first issues`s and am trying to figure out the status of this issue. Looks like @shakalee14 said to hold off on it? Is that still true? If so, I'll close it. In the meantime I'll remove the `good first issue` label

**Comment by joemcl** [comment] 2019-09-02 23:14
Just a note re a possible workaround for this - set the limit for that texter to what has already been sent, and then use Message Review to reassign All Conversations for that texter in that Campaign to another user...might have to then set the texter limit to 0, or 1...

**Comment by Frydafly** [comment] 2021-03-13 18:06
@joemcl is this connected to this newer issue? https://github.com/MoveOnOrg/Spoke/issues/1349 

If so, should I close this issue?

cc: @ibrand

**Comment by schuyler1d** [comment] 2021-03-15 20:35
I believe this is resolved -- at the very least, we'd want to re-confirm as dynamic assignment has been completely rewritten.

**Comment by Frydafly** [comment] 2021-03-16 20:40
Thanks, @schuyler1d! pinging @ErikKirkstein to check on the status before we potentially close this issue

**Comment by Arique1104** [comment] 2021-11-10 02:24
Hello,

My name is Arique (they/them) and I am the Community Manager for Spoke. First of all, thank you so much for creating this issue and for everyone’s contributions to this ticket.

I am going through all of our issues and beginning to close all issues created in 2018 or older. Your issue qualifies.

I am giving everyone one week to answer the following question: 

- **Has this issue been resolved during the subsequent Spoke Updates?**

On November 16th I will be closing this issue if:
1. There is no response
2. You respond yes

If you are reading this message after November 16th, please note that if you tag me and answer the above question, I will be happy to reinstate the issue.

**Comment by Arique1104** [comment] 2021-11-17 01:05
This issue is considered resolved.

**Closed as completed by Arique1104** 2021-11-17 01:05 UTC
Labels: E-estimate: 2 days, A-client side (react), A-server-side (nodejs), A-text assignment, Nov 16 - Candidate
