### ISSUE TITLE
In Campaign -> Texters -> The list of texters is ASCII ordered but not Alphabet ordered.

### ISSUE THREAD

**Issue by theochino** [ProgressiveCoders/Spoke#871] opened 2018-09-07 12:34 UTC
In the list of texter, the list is ordered according to the ASCII table (Uppercase then Lowercase) instead of being Alphabet (case insensitive) ordered.

The list of texters needs to be Alphabet ordered.

**Comment by ibrand** [comment] 2020-05-18 20:11
Closing cause this is a duplicate of #974

**Closed as completed by ibrand** 2020-05-18 20:11 UTC
Labels: A-Admin UI/UX
