### ISSUE TITLE
When creating a campaign, in the interactions form, deleting answer options adds an empty "Start" step and breaks display

### ISSUE THREAD

**Issue by sreynen** [ProgressiveCoders/Spoke#164] opened 2017-08-28 21:21 UTC

**Comment by sreynen** [comment] 2017-09-05 15:42
<img width="651" alt="screen shot 2017-09-05 at 9 41 02 am" src="https://user-images.githubusercontent.com/108645/30069615-740e6e98-921e-11e7-8096-865052ff4df3.png">

Screen shot example. Should never have 2 "Start" steps in a script.

**Comment by ibrand** [comment] 2020-01-22 20:19
This seems to be fixed! I couldn't reproduce it. Closing this one.

**Closed as completed by ibrand** 2020-01-22 20:19 UTC
Labels: C-bug, E-estimate: 1 day
