### ISSUE TITLE
Adding lock mechanism for Supervolunteer race conditions.

### ISSUE THREAD

**Issue by theochino** [ProgressiveCoders/Spoke#874] opened 2018-09-07 20:28 UTC
In order to scale, a locking mechanism needs to be implemented by saving the previous and current state of the distributions of the jobs because two supervolunteers can be assigning work to two different texters and when they both save, they not only override each other, but neither texter has an assignment.

**Comment by ibrand** [comment] 2020-01-24 20:51
Closing because this appears to be a duplicate of #670

**Closed as completed by ibrand** 2020-01-24 20:51 UTC
