### ISSUE TITLE
Bug: Edits made to scripts in the Interactions Menu Do Not Always Save

### ISSUE THREAD

**Issue by shakalee14** [ProgressiveCoders/Spoke#1228] opened 2019-09-13 13:54 UTC
**Describe the bug**
Edits made to scripts in Interactions menu of campaigns are not always saving, causing admins to have to enter the campaign and make the edit multiple times. Sometimes when scripts have been edited, they will revert back to their previous state while texting is going on, causing, for example dates/times to be incorrect, or custom fields not to stay populated when a new custom field is added to a script.

**To Reproduce**
TBD:

**Expected behavior**
New scripts and scripts that have been edited should be updated immediately in the texter outgoing messages.

**Screenshots**
N/A

**Platform (please complete the following information):**
N/A

**Additional context**
This is probably a caching related issue

**Comment by joemcl** [comment] 2019-09-24 21:03
@shakalee14 this may be similar/related - I created a test campaign using a new deploy of v 3.1 on Heroku. I'm using the Chrome browser - Version 77.0.3865.90 (Official Build) (64-bit), Ubuntu 19.04 on my laptop. The test campaign is working as expected. I go into Edit on the Campaign and select Basics to edit. The title of the Campaign is being changed to 'Who are you?' I have 'Who are you?' in my clipboard. It's inserting the clipboard contents text as the Title in Basics when I click to edit Basics. Aargh. If I cancel the edit, it's not saved. But, if I want to edit other parts of Basics, I have to make sure that clipboard text is deleted and the correct, previous Title text is saved.

**Comment by schuyler1d** [comment] 2019-11-20 18:01
I think this was likely resolved with a caching fix.  Would be good to know if people can still replicate this on `main`

**Comment by ibrand** [comment] 2019-11-27 19:39
@joemcl have you seen this error recently? Would love to close the issue if @schuyler1d is right and it did get fixed

**Comment by ibrand** [comment] 2020-01-24 19:49
@joemcl just checking in again about this one

**Comment by JeremyParker** [comment] 2020-07-16 01:29
I'm wondering if this might be related to a confusing UX where it's possible to leave a screen having made edits without the edits being saved.
A set of steps to reproduce this bug reliably would be very helpful in eliminating that possibility.

**Comment by joemcl** [comment] 2020-07-16 01:50
Hi @schuyler1d @ibrand and @JeremyParker. I have not checked on this in awhile, will defer to @suegibson @deasterdaywfp and @bdatkins re any recent occurrence of it. @JeremyParker I do not think the problem was folks not attempting to save edits, though I agree that would be easy to do. I have almost exclusively used importing scripts from a Google doc rather than using the Interactions UI directly over the last six months.

**Comment by ibrand** [comment] 2020-08-26 21:38
Closing cause it appears that this isn't happening anymore for WFP!

**Closed as completed by ibrand** 2020-08-26 21:38 UTC
Labels: C-bug, A-Admin UI/UX, S-needs confirmation
