### ISSUE TITLE
Bug: Team having issues with SPOKE

### ISSUE THREAD

**Issue by Nireia** [ProgressiveCoders/Spoke#2012] opened 2021-06-29 20:17 UTC
I’m managing a team who is using SPOKE and we have been having issues with it lately.

These issues include:

- Reassignment feature not working at all
-  Numerous -1 error codes
- Texters reporting that they are stuck on a conversation and unable to send texts.
- The ability to request new contacts/batches isn’t available despite having a large number of initial texts needing to be sent.

They’ve tried clearing cache and cookies or logging out to log back in, but none of that works. 

I’m new to GitHub so I apologize if this is not the proper place to seek help.

**Comment by arena** [comment] 2021-06-30 18:53
Hi @Nireia 

I'm more expert at design and project stuff ...so, I probably can't help you troubleshoot your technical issues. However, if you want help turning this list into reproducible bugs it will help the community and possibly lead you to known solutions. 

For starters, for each item you listed if you open a single GitHub issue, that would be a good start. If you can describe it in numbered steps that helps even more. Then people will comment on one issue at a time and possibly come up with a fix and/or a workaround to alleviate some of the bad experiences.

**Comment by schuyler1d** [comment] 2021-08-11 15:48
Hi @Nireia 

Welcome!

>    Reassignment feature not working at all

Who is doing reassignment?  We just noticed that SuperVolunteers don't have reassignment privileges (even though they see the reassignment option) -- we plan to fix this in Spoke 11

>  Numerous -1 error codes

This means Twilio or your server is failing to send the message -- it may relate to server setup or because you are 'texting too quickly' -- you might see more details in your Twilio console.

> Texters reporting that they are stuck on a conversation and unable to send texts.

This definitely sounds like a bug -- maybe we can connect to get more details?

> The ability to request new contacts/batches isn’t available despite having a large number of initial texts needing to be sent.

Please try out the experimental `finished-replies-tz` dynamic assignment strategy -- if you have multiple timezones in a campaign, a common issue is that a texter can get assigned contacts that are out of texting hours and then can't get more contacts.  finished-replies-tz fixes this issue.  We might make it the default in the future.

**Closed as completed** 2024-08-07 18:01 UTC
Labels: C-bug
