### ISSUE TITLE
Bug: Reassigned contacts won't load

### ISSUE THREAD

**Issue by jeffm2001** [ProgressiveCoders/Spoke#1251] opened 2019-10-12 18:03 UTC
**Describe the bug**
Most of the time (but not always), when I reassign contacts from the Message Review page, the newly assigned user is not able to act on those contacts. When the new texter clicks on the Send First Texts or Send Replies button, they get a spinner and the message interface never loads.

I strongly suspect this is related to #1250, but since I'm not sure, I'm filing it as a separate issue. Like with #1250, after enough time passes or if I restart the server, the issue resolves itself.

**To Reproduce**
1. Assign contacts to Texter 1, send first messages and wait for replies
2. On the Message Review screen, filter to Needs Texter Response and reassign those contacts to Texter 2
3. Log in as Texter 2 and click Send Replies
4. You will get a spinner that never ends.

**Screenshots**
![2019-10-12 at 1 57 PM](https://user-images.githubusercontent.com/18371709/66705725-75911e00-ecf8-11e9-9958-b9dafc501f6d.png)
![2019-10-12 at 1 58 PM](https://user-images.githubusercontent.com/18371709/66705726-7de95900-ecf8-11e9-86bd-6414362190e5.png)

**Platform (please complete the following information):**
 - OS: Mac and iOS
 - Browser: Chrome and Safari
 - Desktop or Mobile? Both
 - Version 3.1

**Additional context**
I've replicated this issue both on our production instance on Heroku and a test instance running on my local machine.

**Comment by joemcl** [comment] 2019-10-19 01:34
@lperson thoughts on this? I think I'm seeing the same problem...

**Comment by lperson** [comment] 2019-10-19 01:38
@joemcl is this happening on wfp spoke in production?

**Comment by joemcl** [comment] 2019-10-19 01:42
@lperson  happening on another Spoke instance on production, yes

**Comment by joemcl** [comment] 2019-10-19 14:16
So reassigning works almost all the time, but not always, on my production site.

**Comment by lperson** [comment] 2019-10-20 03:28
Reproduced this locally.

**Comment by lperson** [comment] 2019-10-20 03:58
Yes @jeffm2001 and @joemcl this is related to #1250 and the fix is the same.

**Comment by lperson** [comment] 2019-10-22 16:16
This one is different than #1250 in that the root cause is that we're not updating the cache after reassigning the contacts, but this is just a line or two of code missing to update the cache.  See PR #1255 for a discussion about tradeoffs involved in the fix.  (FYI @joshco and @jeffm2001)

**Closed as completed** 2019-12-18 16:12 UTC
Labels: C-bug, O-wfp-priority
