### ISSUE TITLE
You must provide the domain configuration value to use passport-auth0

### ISSUE THREAD

**Issue by ShashiKumar-SignalWire** [ProgressiveCoders/Spoke#1171] opened 2019-07-12 18:17 UTC
While starting with yarn dev-start-debug i am getting this issue `You must provide the domain configuration value to use passport-auth0`

**Comment by jabyess** [comment] 2019-11-07 02:11
This is related to #805 and #1270

**Comment by ibrand** [comment] 2020-01-24 19:43
Closing because this is a duplicate of #753

Also for now as a workaround you can set your local env to use local auth instead of auth0 when developing

**Closed as completed by ibrand** 2020-01-24 19:43 UTC
Labels: A-initial install/setup
