### ISSUE TITLE
MoveOn Spoke: 1/3 of texters joining team are not added to MoveOn Spoke org (Apple users)

### ISSUE THREAD

**Issue by ErikKirkstein** [ProgressiveCoders/Spoke#934] opened 2018-09-21 15:14 UTC
Hi team,

As more new texters are joining the text team, many signing up through iPhones or other Apple products via Safari are not being added to the MoveOn Spoke org. 

As we head into election time, any fix to this would really help in reducing admin time getting these new folks setup to text.

**Comment by shakalee14** [comment] 2018-09-27 13:28
@sandramchung 

@ErikKirkstein was able to forward me a few emails of texters where this has happened because I was not able to reproduce it. Investigating with the emails forwarded, I know a row is created for the user in the DB in user but not user_organization (which is why they get the 'you are not apart of any organization' message). I'm wondering if a 'work' around is to add functionality on the people menu which allows an admin to add a texter by email to the org. Maybe a half step, but helpful.

**Comment by sandramchung** [comment] 2018-09-28 21:58
Still not able to reproduce this or find anything useful in the instance logs. For the workaround - how should that work? Search existing users by email/cell # and then add them to the org  (I'm assuming we don't allow admins to create users from scratch since users still need connected auth0 creds)? One at a time or bulk? Perhaps we could pre-load it with results of a search for users who have no assigned org. It'd be simpler to run a cron job specific to our instance that periodically checks the db for users with no assigned org and automatically assigns them to the MoveOn Spoke org as texters.

**Comment by sandramchung** [comment] 2018-09-28 22:00
Could also add some backend logging to try and catch this bug in action.

**Comment by sandramchung** [comment] 2018-09-28 22:50
Looking at the 99 users in our instance who don't have orgs, they appear pretty sporadically over the past few months except there are more than usual on 9/26, 9/27 and 9/28. Could be because of manual fixes, I don't know for sure.

**Comment by sandramchung** [comment] 2018-10-08 16:48
https://github.com/MoveOnOrg/Spoke/pull/966 Adds logging to help get to the root of the issue and creates a temporary fix in the form of a cron job that adds orgless users to the default org.

**Comment by shakalee14** [comment] 2019-03-14 17:33
Fixed with #1039

**Closed as completed by shakalee14** 2019-03-14 17:33 UTC
