### ISSUE TITLE
Push replies to texter

### ISSUE THREAD

**Issue by ben-pr-p** [ProgressiveCoders/Spoke#466] opened 2018-01-14 23:20 UTC
If someone has just finished texting a list, and they are sitting on the post completion page, they have to refresh in order for "Send Replies" to pop up.

This could include:
- [ ] Push updates live to user (Send Replies pops up without requiring a refresh)
- [ ] Send the texter a push notification

**Comment by shakalee14** [comment] 2018-02-24 18:54
https://github.com/MoveOnOrg/Spoke/issues/254
Original discussion around this issue.

**Comment by ibrand** [comment] 2020-05-18 19:45
Closing because this is a duplicate of #207

**Closed as completed by ibrand** 2020-05-18 19:45 UTC
Labels: C-use case, S-needs planning, O-justicedemocrats:priority, A-Texter UI/UX, A-notifications
