### ISSUE TITLE
'Cancel' button when creating canned response scripts doesn't work

### ISSUE THREAD

**Issue by rifkegribenes** [ProgressiveCoders/Spoke#568] opened 2018-04-11 22:45 UTC
![screen shot 2018-04-11 at 3 42 58 pm](https://user-images.githubusercontent.com/24995773/38647025-19238518-3d9f-11e8-8544-8c2f10bd24d3.png)
When creating a new canned response, 'Cancel' button does not clear the form or remove the form container. The only way to exit is to continue creating the response, add it, and then delete it afterwards.

**Comment by ibrand** [comment] 2020-01-24 20:11
Closing since I can't reproduce this, so I think it's been fixed!

**Closed as completed by ibrand** 2020-01-24 20:11 UTC
