### ISSUE TITLE
Bug: Texter TODO list no longer auto-reloads every 5 seconds

### ISSUE THREAD

**Issue by tekkamanendless** [ProgressiveCoders/Spoke#1712] opened 2020-08-03 03:27 UTC
**Describe the bug**
The intent of the texter TODO list is to present a kind of dashboard of the texts that they have available to deal with.  For example, after replying to all of the text messages, the texter shoudl be able to remain on that screen, and as replies come in, the screen should update with the appropriate buttons and badges (for example, "Respond (1)").

After combing through the source code, it looks like this functionality was broken on June 3, 2019, with a change to how user data is cached.

Short version of the story:
1. [src/containers/TexterTodoList.jsx](https://github.com/MoveOnOrg/Spoke/blame/main/src/containers/TexterTodoList.jsx#L57) contains this line to control the auto-refresh:
    ```if (this.props.data.currentUser.cacheable && !this.state.polling) {```
2. Thus, it will begin auto-refresh if (1) `cacheable` is true and (2) auto-refresh hasn't started yet.
3. [src/server/api/user.js](https://github.com/MoveOnOrg/Spoke/blame/main/src/server/api/user.js#L274) forces `cacheable` to be false no matter what.
4. Thus, auto-refresh will never begin.

**To Reproduce**
1. Create a texting campaign, assign a user 2 contacts.
2. As that user, send the "first message" to 1 of the contacts.
3. Go back to the `todos` screen.
4. See that there is 1 "first text" still to send, and nothing to reply to.
5. As the contact, reply to that first message.
6. Wait 10 seconds.
7. As the user, note that the `todos` screen has not changed, even though a reply has come back.

**Expected behavior**
Step (7) above should instead show a "Respond (1)" button, telling the user that there has been a response to that first text message.

**Screenshots**
n/a

**Platform (please complete the following information):**
 - OS: Linux (but applies to all OSes)
 - Browser: Chrome (but applies to all browsers)
 - Desktop or Mobile: Desktop (but applies to all architectures)
 - Version: 84 (but applies to all versions)

**Additional context**
This is the first relevant change (on April 24, 2019): https://github.com/MoveOnOrg/Spoke/commit/4f9585db3cf6564282264cf07d6f8410619e5fb4
This change introduces the requirement around `cacheable` needing to be true in order to start auto-refresh ("polling").

This is the second relevant change (on June 3, 2019): https://github.com/MoveOnOrg/Spoke/commit/dbbb20acb2bde3ca3daf5936dc115dadcfb2590c
This change forces `cacheable` to always be false.

My take is that the `todos` screen shouldn't care at all about `cacheable`, since we know for a fact that the data should be refreshed no matter what on that screen.

On my machine, I've simply removed the `this.props.data.currentUser.cacheable && ` part, and it's working as expected now.

**Comment by schuyler1d** [comment] 2020-08-04 21:02
This is a duplicate of: https://github.com/MoveOnOrg/Spoke/issues/207

Unfortunately, it's more complicated than that.  It wasn't "broken" but rather without the data cached in some way, turning this on does not scale -- imagine 1000s of texters on the todo screen polling an API every 20 seconds that requires a lot of large SQL queries.

That said, that issue is not up-to-date, and we should describe the current plan -- which we'd welcome help on!

**Closed as completed by schuyler1d** 2020-08-04 21:02 UTC
Labels: C-bug

**Comment by schuyler1d** [comment] 2020-08-04 21:18
See "Possible solution" in the description which I just added in #207.  If you have another idea, please propose in a new issue and `@` me, please.
