### ISSUE TITLE
Should not have to send a message for opt-out

### ISSUE THREAD

**Issue by schuyler1d** [ProgressiveCoders/Spoke#599] opened 2018-05-23 01:06 UTC
Currently it's impossible to opt-out a contact without sending them a final message.

It would be good to allow opt-out without having to send a message.
This issue is probably entirely client-side.
In [src/containers/AssignmentTexterContact:handleOptOut](https://github.com/MoveOnOrg/Spoke/blob/main/src/containers/AssignmentTexterContact.jsx#L434-L456)  you'll notice that it sends a message and then createOptOut, etc.

We should have an additional button "Opt out without sending message" or something similar in the interface which createOptOut but without sending a message.  Alternatively we could document that if no message content is included, then we don't send a message, but still opt them out.

**Comment by shakalee14** [comment] 2018-05-30 16:32
this issue is a duplicate of https://github.com/MoveOnOrg/Spoke/issues/577

**Closed as completed** 2018-05-30 16:32 UTC
Labels: C-bug, E-easy, A-client side (react), good first issue
